"""add: photo table

Revision ID: 23df4a2134dc
Revises: eda457cf470a
Create Date: 2025-12-05 22:40:54.994979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23df4a2134dc'
down_revision: Union[str, Sequence[str], None] = 'eda457cf470a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_photo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('events_photo_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('events_photo_pkey')),
    sa.UniqueConstraint('url', name=op.f('events_photo_url_key'))
    )
    op.create_index(op.f('events_photo_event_id_idx'), 'events_photo', ['event_id'], unique=False)
    op.create_index(op.f('events_photo_object_name_idx'), 'events_photo', ['object_name'], unique=True)
    op.drop_column('events', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('photo_path', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index(op.f('events_photo_object_name_idx'), table_name='events_photo')
    op.drop_index(op.f('events_photo_event_id_idx'), table_name='events_photo')
    op.drop_table('events_photo')
    # ### end Alembic commands ###
