"""add: reviews

Revision ID: 24e1c4f73358
Revises: 00a2f52e786f
Create Date: 2025-11-23 16:14:36.816794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e1c4f73358'
down_revision: Union[str, Sequence[str], None] = '00a2f52e786f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('events_reviews_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('events_reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('events_reviews_pkey'))
    )
    op.create_index(op.f('events_reviews_event_id_idx'), 'events_reviews', ['event_id'], unique=False)
    op.create_index(op.f('events_reviews_user_id_idx'), 'events_reviews', ['user_id'], unique=False)
    op.add_column('events', sa.Column('average_rating', sa.Float(), nullable=True))
    op.create_index(op.f('events_average_rating_idx'), 'events', ['average_rating'], unique=False)
    op.add_column('user', sa.Column('is_organizer', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_organizer')
    op.drop_index(op.f('events_average_rating_idx'), table_name='events')
    op.drop_column('events', 'average_rating')
    op.drop_index(op.f('events_reviews_user_id_idx'), table_name='events_reviews')
    op.drop_index(op.f('events_reviews_event_id_idx'), table_name='events_reviews')
    op.drop_table('events_reviews')
    # ### end Alembic commands ###
