"""add: reviews

Revision ID: 390e6ba7545d
Revises: 24e1c4f73358
Create Date: 2025-11-23 20:47:51.485383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390e6ba7545d'
down_revision: Union[str, Sequence[str], None] = '24e1c4f73358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('count_reviews', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'count_reviews')
    # ### end Alembic commands ###
