"""add new table Event

Revision ID: 440cc95323f5
Revises: 11edf64cf14b
Create Date: 2025-11-03 23:58:03.471899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440cc95323f5'
down_revision: Union[str, Sequence[str], None] = '11edf64cf14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('Capacity', sa.Float(), nullable=False),
    sa.Column('Photo_Path', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('environment', sa.Enum('indoor', 'outdoor', 'semi_door', name='eventenvironment'), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('age_rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('Event_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Event_pkey'))
    )
    op.create_index(op.f('Event_Capacity_idx'), 'Event', ['Capacity'], unique=False)
    op.create_index(op.f('Event_age_rating_idx'), 'Event', ['age_rating'], unique=False)
    op.create_index(op.f('Event_end_idx'), 'Event', ['end'], unique=False)
    op.create_index(op.f('Event_environment_idx'), 'Event', ['environment'], unique=False)
    op.create_index(op.f('Event_id_idx'), 'Event', ['id'], unique=False)
    op.create_index(op.f('Event_latitude_idx'), 'Event', ['latitude'], unique=False)
    op.create_index(op.f('Event_longitude_idx'), 'Event', ['longitude'], unique=False)
    op.create_index(op.f('Event_name_idx'), 'Event', ['name'], unique=False)
    op.create_index(op.f('Event_start_idx'), 'Event', ['start'], unique=False)
    op.add_column('refresh_session', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('refresh_session', 'updated_at')
    op.drop_index(op.f('Event_start_idx'), table_name='Event')
    op.drop_index(op.f('Event_name_idx'), table_name='Event')
    op.drop_index(op.f('Event_longitude_idx'), table_name='Event')
    op.drop_index(op.f('Event_latitude_idx'), table_name='Event')
    op.drop_index(op.f('Event_id_idx'), table_name='Event')
    op.drop_index(op.f('Event_environment_idx'), table_name='Event')
    op.drop_index(op.f('Event_end_idx'), table_name='Event')
    op.drop_index(op.f('Event_age_rating_idx'), table_name='Event')
    op.drop_index(op.f('Event_Capacity_idx'), table_name='Event')
    op.drop_table('Event')
    # ### end Alembic commands ###
