"""edit

Revision ID: c22131b58263
Revises: e9a0b1565995
Create Date: 2025-11-05 20:22:28.799301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22131b58263'
down_revision: Union[str, Sequence[str], None] = 'e9a0b1565995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('Event_address_idx'), 'Event', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('Event_address_idx'), table_name='Event')
    op.drop_column('Event', 'is_active')
    # ### end Alembic commands ###
