"""add new table Event

Revision ID: e9a0b1565995
Revises: 440cc95323f5
Create Date: 2025-11-04 10:34:37.213501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9a0b1565995'
down_revision: Union[str, Sequence[str], None] = '440cc95323f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('capacity', sa.Float(), nullable=False))
    op.add_column('Event', sa.Column('photo_path', sa.ARRAY(sa.String()), nullable=False))
    op.drop_index(op.f('Event_Capacity_idx'), table_name='Event')
    op.create_index(op.f('Event_capacity_idx'), 'Event', ['capacity'], unique=False)
    op.drop_column('Event', 'Capacity')
    op.drop_column('Event', 'Photo_Path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('Photo_Path', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('Event', sa.Column('Capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('Event_capacity_idx'), table_name='Event')
    op.create_index(op.f('Event_Capacity_idx'), 'Event', ['Capacity'], unique=False)
    op.drop_column('Event', 'photo_path')
    op.drop_column('Event', 'capacity')
    # ### end Alembic commands ###
