"""add: favorites

Revision ID: eda457cf470a
Revises: 390e6ba7545d
Create Date: 2025-11-24 17:21:15.246046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda457cf470a'
down_revision: Union[str, Sequence[str], None] = '390e6ba7545d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_favorite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('user_event_favorite_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_event_favorite_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_event_favorite_pkey'))
    )
    op.create_index(op.f('user_event_favorite_event_id_idx'), 'user_event_favorite', ['event_id'], unique=False)
    op.create_index(op.f('user_event_favorite_id_idx'), 'user_event_favorite', ['id'], unique=False)
    op.create_index(op.f('user_event_favorite_user_id_idx'), 'user_event_favorite', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_event_favorite_user_id_idx'), table_name='user_event_favorite')
    op.drop_index(op.f('user_event_favorite_id_idx'), table_name='user_event_favorite')
    op.drop_index(op.f('user_event_favorite_event_id_idx'), table_name='user_event_favorite')
    op.drop_table('user_event_favorite')
    # ### end Alembic commands ###
